version: '3'

services:
  database:
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./packages/database/volumes:/var/lib/postgresql/data

volumes:
  database:
